import type { Metadata } from "next";
import { Inter, Montserrat, Roboto, Blinker } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/smoothScroll/smoothScroll";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
});

const roboto = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto",
});
const blinker = Blinker({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
    variable: "--font-blinker",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="h-full antialiased">
            <body
                className={`${inter.variable} ${montserrat.variable} ${roboto.variable} ${blinker.variable} min-h-full`}
            >
                <SmoothScroll>{children}</SmoothScroll>
            </body>
        </html>
    );
}
